In [1]:
import pandas as pd

gen = pd.read_csv("../data/raw/Plant_1_Generation_Data.csv")
weather = pd.read_csv("../data/raw/Plant_1_Weather_Sensor_Data.csv")

gen["DATE_TIME"] = pd.to_datetime(
    gen["DATE_TIME"],
    format="%d-%m-%Y %H:%M"
)

weather["DATE_TIME"] = pd.to_datetime(
    weather["DATE_TIME"],
    format="%Y-%m-%d %H:%M:%S"
)

In [2]:
gen.info()

<class 'pandas.DataFrame'>
RangeIndex: 68778 entries, 0 to 68777
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DATE_TIME    68778 non-null  datetime64[us]
 1   PLANT_ID     68778 non-null  int64
 2   SOURCE_KEY   68778 non-null  str
 3   DC_POWER     68778 non-null  float64
 4   AC_POWER     68778 non-null  float64
 5   DAILY_YIELD  68778 non-null  float64
 6   TOTAL_YIELD  68778 non-null  float64
dtypes: datetime64[us](1), float64(4), int64(1), str(1)
memory usage: 3.7 MB

In [3]:
weather.info()

<class 'pandas.DataFrame'>
RangeIndex: 3182 entries, 0 to 3181
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   DATE_TIME            3182 non-null   datetime64[us]
 1   PLANT_ID             3182 non-null   int64
 2   SOURCE_KEY           3182 non-null   str
 3   AMBIENT_TEMPERATURE  3182 non-null   float64
 4   MODULE_TEMPERATURE   3182 non-null   float64
 5   IRRADIATION          3182 non-null   float64
dtypes: datetime64[us](1), float64(3), int64(1), str(1)
memory usage: 149.3 KB

In [4]:
gen.isnull().sum()

DATE_TIME      0
PLANT_ID       0
SOURCE_KEY     0
DC_POWER       0
AC_POWER       0
DAILY_YIELD    0
TOTAL_YIELD    0
dtype: int64

In [5]:
weather.isnull().sum()

DATE_TIME              0
PLANT_ID               0
SOURCE_KEY             0
AMBIENT_TEMPERATURE    0
MODULE_TEMPERATURE     0
IRRADIATION            0
dtype: int64

In [6]:
gen.duplicated().sum()

np.int64(0)

In [7]:
weather.duplicated().sum()

np.int64(0)

In [8]:
gen.describe()

,DATE_TIME,PLANT_ID,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD
count,68778,68778.0,68778.000000,68778.000000,68778.000000,6.877800e+04
mean,2020-06-01 08:02:49.458257,4135001.0,3147.426211,307.802752,3295.968737,6.978712e+06
min,2020-05-15 00:00:00,4135001.0,0.000000,0.000000,0.000000,6.183645e+06
25%,2020-05-24 00:45:00,4135001.0,0.000000,0.000000,0.000000,6.512003e+06
50%,2020-06-01 14:30:00,4135001.0,429.000000,41.493750,2658.714286,7.146685e+06
75%,2020-06-09 20:00:00,4135001.0,6366.964286,623.618750,6274.000000,7.268706e+06
max,2020-06-17 23:45:00,4135001.0,14471.125000,1410.950000,9163.000000,7.846821e+06
std,NaN,0.0,4036.457169,394.396439,3145.178309,4.162720e+05

In [9]:
weather.describe()

,DATE_TIME,PLANT_ID,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
count,3182,3182.0,3182.000000,3182.000000,3182.000000
mean,2020-06-01 05:52:22.080452,4135001.0,25.531606,31.091015,0.228313
min,2020-05-15 00:00:00,4135001.0,20.398505,18.140415,0.000000
25%,2020-05-23 22:48:45,4135001.0,22.705182,21.090553,0.000000
50%,2020-06-01 09:52:30,4135001.0,24.613814,24.618060,0.024653
75%,2020-06-09 16:56:15,4135001.0,27.920532,41.307840,0.449588
max,2020-06-17 23:45:00,4135001.0,35.252486,65.545714,1.221652
std,NaN,0.0,3.354856,12.261222,0.300836

In [10]:
negative_counts = {
    "AC_POWER": (gen["AC_POWER"] < 0).sum(),
    "DC_POWER": (gen["DC_POWER"] < 0).sum(),
    "DAILY_YIELD": (gen["DAILY_YIELD"] < 0).sum(),
    "TOTAL_YIELD": (gen["TOTAL_YIELD"] < 0).sum()
}

negative_counts

{'AC_POWER': np.int64(0),
 'DC_POWER': np.int64(0),
 'DAILY_YIELD': np.int64(0),
 'TOTAL_YIELD': np.int64(0)}

In [11]:
neg_counts={
    "Ambient_Temp":(weather["AMBIENT_TEMPERATURE"] < 0).sum(),
    "Module_Temp":(weather["MODULE_TEMPERATURE"] < 0).sum(),
    "Irradiation":(weather["IRRADIATION"] < 0).sum()
}

neg_counts

{'Ambient_Temp': np.int64(0),
 'Module_Temp': np.int64(0),
 'Irradiation': np.int64(0)}

In [12]:
gen["SOURCE_KEY"].nunique()

22

In [13]:
weather["SOURCE_KEY"].nunique()

1

In [14]:
gen.to_csv("../data/cleaned/Plant_1_Generation_Cleaned.csv", index=False)
weather.to_csv("../data/cleaned/Plant_1_Weather_Cleaned.csv", index=False)