In [2]:
import pandas as pd
import numpy as np

gen = pd.read_csv("../data/cleaned/Plant_1_Generation_Cleaned.csv")
weather = pd.read_csv("../data/cleaned/Plant_1_Weather_Cleaned.csv")

gen["DATE_TIME"] = pd.to_datetime(gen["DATE_TIME"])
weather["DATE_TIME"] = pd.to_datetime(weather["DATE_TIME"])

merged = pd.merge(
    gen,
    weather,
    on=["DATE_TIME", "PLANT_ID"],
    how="inner"
)

merged.head()

,DATE_TIME,PLANT_ID,SOURCE_KEY_x,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,SOURCE_KEY_y,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
0,2020-05-15,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
1,2020-05-15,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
2,2020-05-15,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6987759.0,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
3,2020-05-15,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7602960.0,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
4,2020-05-15,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7158964.0,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0

In [3]:
merged["HOUR"] = merged["DATE_TIME"].dt.hour
merged["DAY"] = merged["DATE_TIME"].dt.day
merged["MONTH"] = merged["DATE_TIME"].dt.month
merged["WEEKDAY"] = merged["DATE_TIME"].dt.weekday

merged["IS_WEEKEND"] = (
    merged["WEEKDAY"] >= 5
).astype(int)

merged.head()

,DATE_TIME,PLANT_ID,SOURCE_KEY_x,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,SOURCE_KEY_y,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION,HOUR,DAY,MONTH,WEEKDAY,IS_WEEKEND
0,2020-05-15,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,0,15,5,4,0
1,2020-05-15,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,0,15,5,4,0
2,2020-05-15,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6987759.0,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,0,15,5,4,0
3,2020-05-15,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7602960.0,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,0,15,5,4,0
4,2020-05-15,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7158964.0,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,0,15,5,4,0

In [4]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

merged["SOURCE_KEY_x"] = encoder.fit_transform(
    merged["SOURCE_KEY_x"]
)

merged.head()

,DATE_TIME,PLANT_ID,SOURCE_KEY_x,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,SOURCE_KEY_y,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION,HOUR,DAY,MONTH,WEEKDAY,IS_WEEKEND
0,2020-05-15,4135001,0,0.0,0.0,0.0,6259559.0,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,0,15,5,4,0
1,2020-05-15,4135001,1,0.0,0.0,0.0,6183645.0,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,0,15,5,4,0
2,2020-05-15,4135001,2,0.0,0.0,0.0,6987759.0,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,0,15,5,4,0
3,2020-05-15,4135001,3,0.0,0.0,0.0,7602960.0,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,0,15,5,4,0
4,2020-05-15,4135001,4,0.0,0.0,0.0,7158964.0,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,0,15,5,4,0

In [5]:
merged = merged.drop(columns=["DATE_TIME"])

merged.info()

<class 'pandas.DataFrame'>
RangeIndex: 68774 entries, 0 to 68773
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   PLANT_ID             68774 non-null  int64
 1   SOURCE_KEY_x         68774 non-null  int64
 2   DC_POWER             68774 non-null  float64
 3   AC_POWER             68774 non-null  float64
 4   DAILY_YIELD          68774 non-null  float64
 5   TOTAL_YIELD          68774 non-null  float64
 6   SOURCE_KEY_y         68774 non-null  str
 7   AMBIENT_TEMPERATURE  68774 non-null  float64
 8   MODULE_TEMPERATURE   68774 non-null  float64
 9   IRRADIATION          68774 non-null  float64
 10  HOUR                 68774 non-null  int32
 11  DAY                  68774 non-null  int32
 12  MONTH                68774 non-null  int32
 13  WEEKDAY              68774 non-null  int32
 14  IS_WEEKEND           68774 non-null  int64
dtypes: float64(7), int32(4), int64(3), str(1)
memory usage: 6.8 MB

In [6]:
merged.to_csv(
    "../data/cleaned/Plant_1_Feature_Engineered.csv",
    index=False
)